# https://docs.docker.com/compose/compose-file

version: '3'

services:

  redis:
    image: redis:5
    ports:
      - "6379:6379"
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ${PWD}/database:/database