"""empty message

Revision ID: 5b3c392c4bde
Revises: 
Create Date: 2020-04-14 13:58:19.902055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3c392c4bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'building', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'building_floor', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'building_floor_connector', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'elevator', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'elevator_floor', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'floor_facility', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'robot', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'site', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'site_facility_unit', ['uuid'], schema='public')
    op.create_unique_constraint(None, 'site_group', ['uuid'], schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_group', schema='public', type_='unique')
    op.drop_constraint(None, 'site_facility_unit', schema='public', type_='unique')
    op.drop_constraint(None, 'site', schema='public', type_='unique')
    op.drop_constraint(None, 'robot', schema='public', type_='unique')
    op.drop_constraint(None, 'floor_facility', schema='public', type_='unique')
    op.drop_constraint(None, 'elevator_floor', schema='public', type_='unique')
    op.drop_constraint(None, 'elevator', schema='public', type_='unique')
    op.drop_constraint(None, 'building_floor_connector', schema='public', type_='unique')
    op.drop_constraint(None, 'building_floor', schema='public', type_='unique')
    op.drop_constraint(None, 'building', schema='public', type_='unique')
    # ### end Alembic commands ###
