"""empty message

Revision ID: a11826484f91
Revises: b352a3a93ed9
Create Date: 2020-04-07 00:13:22.301728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a11826484f91'
down_revision = 'b352a3a93ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('building_floors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elevators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chargers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_doors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('building_floor',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('floor_index', sa.Integer(), nullable=False),
    sa.Column('connected_floors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('floor_facilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('building_floor_connector',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_uuid_1', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('floor_uuid_1', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_uuid_2', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('floor_uuid_2', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('elevator',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('elevator_floors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('elevator_floor',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('elevator_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('floor_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('building_floor_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_reachable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('floor_facility',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit_type', sa.SmallInteger(), nullable=False),
    sa.Column('direction', sa.SmallInteger(), nullable=False),
    sa.Column('building_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_floor_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('robot',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('robot_type', sa.SmallInteger(), nullable=False),
    sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('site',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('has_building_connector', sa.Boolean(), nullable=False),
    sa.Column('business_types', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('section_site', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_building', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_facility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_iot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('site_facility_unit',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('site_uid', sa.BigInteger(), nullable=False),
    sa.Column('facility_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('group_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('facility_sid', sa.Integer(), nullable=True),
    sa.Column('facility_group_index', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.Integer(), nullable=False),
    sa.Column('unit_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('unit_uid', sa.BigInteger(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('unit_uid'),
    sa.UniqueConstraint('unit_uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_table('site_group',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_uuid', sa.String(length=50), nullable=True),
    sa.Column('creator_ugid', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('meta_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('site_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('building_floor_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('facility_group_sid', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.SmallInteger(), nullable=False),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_group', schema='public')
    op.drop_table('site_facility_unit', schema='public')
    op.drop_table('site', schema='public')
    op.drop_table('robot', schema='public')
    op.drop_table('floor_facility', schema='public')
    op.drop_table('elevator_floor', schema='public')
    op.drop_table('elevator', schema='public')
    op.drop_table('building_floor_connector', schema='public')
    op.drop_table('building_floor', schema='public')
    op.drop_table('building', schema='public')
    # ### end Alembic commands ###
