"""empty message

Revision ID: b352a3a93ed9
Revises: fe9dc567c8f1
Create Date: 2020-04-06 23:46:40.154289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b352a3a93ed9'
down_revision = 'fe9dc567c8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('robot_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='robot_pkey')
    )
    # ### end Alembic commands ###
